name: PHP

on:
  pull_request: { }
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  php-library:
    uses: equisoft-actions/php-workflows/.github/workflows/php-library.yml@9b9d3024ab40d6e142f6c50783b7a0fbabec3c81 # v4
    with:
      checks: phpcs,phpunit,psalm
      php-version: '8.1'
      extensions: pcov
    secrets:
      GPR_KEY: ${{ secrets.GPR_KEY }}
